name: 'Linting & test'

on: push

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # githubs own action plugin - a way Github knows to get all your code from github, and run actions on it - S ON ACTIONS!
      - name: 'Installs packages'
        run: npm install
      - name: 'Execute linter'
        run: npm run lint

  E2E-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Install packages'
        run: npm intall
      - uses: cypress-io/github-action@v6 # Cypress way to run you e2e test - cypress plugin that automaticly runs your cypress-e2e test - NO S IN ACTION!
        with: 
          start: npm run dev
    